#!/bin/sh

./.config/X11/screen-main.sh
#xset s off
xset dpms 0 0 300
xset r rate 280 40
setxkbmap -option caps:none

userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

[ -f ~/.config/X11/profile ] && source ~/.config/X11/profile

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

case $(tty) in
    /dev/tty3 ) exec env XDG_CURRENT_DESKTOP=i3 i3;;
    *) :;;
esac
