#!/bin/bash
command -v exa &>/dev/null && alias ls='exa -F --time-style=long-iso' \
        alias la='exa -F -a --time-style=long-iso' \
        alias ll='exa -F -alg --time-style=long-iso' \
        alias tree='exa -T --time-style=long-iso' \
alias cp='cp -v'
alias mv='mv -v'
command -v rip &>/dev/null && alias rm='rip'
alias mkdir='mkdir -vp'
command -v tree &> /dev/null && alias k='tree'
command -v nvim &>/dev/null && alias vi='nvim' && alias vim='nvim'
alias gksu='pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY GTK_THEME=$GTK_THEME WAYLAND_DISPLAY=$WAYLAND_DISPLAY XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR'
command -v bat &>/dev/null && alias cat='bat --theme Nord'
alias diff='diff --color=auto'
alias yayskip='yay -S --mflags "--skipchecksums --skippgpcheck"'
alias wine='WINEPREFIX=$HOME/.local/share/wine wine'
alias wine64='WINEPREFIX=$HOME/.local/share/wine64 wine64'
alias ip='ip --color=auto'
alias l='ls'
alias ln='ln -nv'
command -v git &>/dev/null && alias gs='git status' \
        alias gA='git add -A' \
        alias ga='git add' \
        alias gb='git branch' \
        alias gc='git commit' \
        alias gd='git diff' \
        alias gco='git checkout' \
        alias gl='git pull' \
        alias gp='git push' \
        alias gi='git' \
        alias g='git' \
alias yay='paru'
function yta() {
    mpv --ytdl-format=bestaudio ytdl://ytsearch:"$*"
}
alias :q='exit'
alias chmod='chmod -c'
alias chown='chown -c'
alias zr='z $(ghq list -p | fzf)'
alias du='dua'
alias lg='lazygit'
alias chattr='chattr -V'
function mkcd(){mkdir $1 && cd $_}
if [[ ${XDG_SESSION_TYPE} == "wayland" ]]; then
        alias clip='wl-copy'
else
        alias clip='xclip -sel c'
fi
alias a='cd ../'
alias aa='cd ../../'
alias aaa='cd ../../../'
alias aaaa='cd ../../../../'
alias aaaaa='cd ../../../../../'
alias doas='doas '
alias gksu >/dev/null && alias veracrypt='gksu veracrypt'
alias ztmp='z $(mktemp -d)'
alias man='man -L ja_JP.UTF-8'
alias oct='stat -c "%A %a %n"'
alias pn='pnpm'
alias ctf='doas openvpn $1'
alias md='mkdir'
alias explorer='pcmanfm-qt'
